---
format: 
  wildflower-revealjs:
    footer: <https://saranjeetkaur.github.io/flower-report/>
    embed-resources: true
---

## Creating Parameterised Reports Using Quarto {.flores-slide8 .center}

### Bristol R User Group

16 July 2025

Saranjeet Kaur Bhogal

Imperial College London

## Parameterised reports {.flores-slide2 .center}

::: {.fragment}
### What?
:::

::: {.fragment}
Single template report -> render multiple outputs
:::

::: {.fragment}
Automate using `params`
:::

::: {.fragment}
### Why?
:::

::: {.fragment}
Accurate, Reproducible, Automated
:::

::: {.fragment}
No repetitive copy-paste, less prone to error
:::

## Example use cases {.flores-slide1 .center}

::: {.fragment}
- Periodic (e.g. weekly, monthly) analytics
:::

::: {.fragment}
- Regional (e.g. country, state) reports
:::

::: {.fragment}
- Scientific reports for different species (e.g. plants, flowers)
:::

## Flower dataset {.flores-section1 .center}

::: {.fragment} 
Kaggle: [Synthetic flower dataset](https://www.kaggle.com/datasets/abhayayare/flower-dataset)
:::

::: {.fragment} 
```markdown
species,size,fragrance,height_cm
rose, medium, mild, 48.55
shoeblack plant, medium, mild, 147.07
shoeblack plant, medium, none, 102.93
hibiscus, large, none, 184.0
```
:::

## Metadata {.flores-section1 .center}

::: {.fragment}
`species`: Type of flower (`hibiscus`, `rose`, or `shoeblack plant`)
:::

::: {.fragment}
`size`: Size category (`small`, `medium`, or `large`)
:::

::: {.fragment}
`fragrance`: Intensity of the fragrance (`strong`, `mild`, or `none`)
:::

::: {.fragment}
`height_cm`: Height of flower in centimeters (rounded to 2 decimal places)
:::

## Objective {.flores-slide3 .center}

::: {.fragment}
For each species of the flowers, create a report giving a details about their 
summary and height distribution.
:::

## A .qmd file {.flores-slide2 .center}

**Without params**

````r
---
title: "Flower Species Report: rose"
format: html
---

## Load dataset

```r
library(tidyverse)
df <- read_csv("data/flower_dataset.csv")
```

## Filter for species: rose
```
df_rose <- df %>% filter(species == "rose")
```

## Height distribution for rose

```r
ggplot(df_rose, aes(height_cm)) +
  geom_histogram()
```
````

## With params {.flores-slide2 .center}

````r
---
title: "Flower Species Report: `r params$sp`"
format: html
params:
	sp: "rose"
---

## Load dataset

```r
library(tidyverse)
df <- read_csv("data/flower_dataset.csv")
```

## Filter for species: `r params$sp`
```
df_filtered <- df %>% filter(species == params$sp)
```

## Height distribution for `r params$sp`

```r
ggplot(df_filtered, aes(height_cm)) +
  geom_histogram()
```
````

## {.flores-section1 .center}

### Render reports

```r
library(quarto)
library(tidyverse)

# Species names
species <- c("rose", "shoeblack plant", "hibiscus")

# Create a tibble
reports <- tibble(
  input = "flower-report.qmd",
  output_file = stringr::str_glue("{species}.html"),
  execute_params = purrr::map(species, ~list(sp = .))
)

# Render each report
purrr::pwalk(reports, quarto_render)
```

## {.flores-title2 .center}

### Let's run some code!

## Bonus! {.flores-title1 .center}

## {.flores-title4 .center}

### Branding with `_brand.yml`

## `_brand.yml`? {.flores-section2 .center}

::: {.fragment}
A simple, portable YAML file that codifies brand guidelines (customised) into a format that can be used by Quarto to create branded outputs (for our purpose, reports)
:::

## {.flores-section1 .center}

### _brand.yml

```markdown
meta:
  name: Example organisation
  link: https://posit-dev.github.io/brand-yml

logo: logos/logo.png

color:
  palette:
    black: "#1A1A1A"
    white: "#F9F9F9"
    orange: "#FF6F20"
    pink: "#FF3D7F"
  foreground: black
  background: white
  primary: orange

typography:
  fonts:
    - family: Open Sans
      source: google
```

## {.flores-section3 .center}

### Branding resources

::: {.fragment}
[BRAND.YML webpage](https://posit-dev.github.io/brand-yml/)
:::

## Let's experiment! {.flores-title1 .center}

## Advantages of branding {.flores-slide1 .center}

::: {.fragment}
- Consistent branding across outputs
:::

::: {.fragment}
- Shared consistency within teams
:::

::: {.fragment}
- Minimal effort
:::

## Resources {.flores-slide3 .center}

Blog: [Automating Quarto reports with parameters](https://posit.co/blog/parameterized-quarto/)

Video: [A step-by-step guide to parameterized reporting in R using Quarto](https://www.youtube.com/watch?v=7dkufBboMi4)

Video: [Company-branded reports, apps, and dashboards made easier with brand.yml & Posit](https://www.youtube.com/watch?v=U48y0_yzEPY)

Brand.yml Website: <https://posit-dev.github.io/brand-yml/>

## Slides {.flores-section3}

::: {.fragment}
Slides made using [quarto](https://github.com/quarto-dev/quarto) and [Wildflower](https://github.com/ariibard/quarto-revealjs-wildflowers) theme
:::

## Thank you! {.flores-slide5 .center}

**Talk link**: https://saranjeetkaur.github.io/flower-report/

**Talk repository**: https://github.com/SaranjeetKaur/flower-report

**GitHub**: SaranjeetKaur

**Email**: kaur.saranjeet3\@gmail.com
